enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1
cli-source = "MorpheApp/morphe-cli"
patches-source = "MorpheApp/morphe-patches"
rv-brand = "Morphe"

[YouTube]
build-mode = "both"
excluded-patches = ""
included-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[YouTube-Music]
build-mode = "both"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
